### DISCUSSION TITLE
tls WS direct vmess doesn't work

### DISCUSSION THREAD

**Discussion by meness** [hiddify/Hiddify-Manager#3604] [General سایر]
```
- name: "x tls WS direct vmess \xA7 443 4"
    type: vmess
    server: x.jerkface.net
    port: 443
    uuid: x
    servername: x.jerkface.net
    tls: true
    alterId: 0
    cipher: chacha20-poly1305
    skip-cert-verify: false
    network: ws
    ws-opts:
      path: /x
      headers:
        Host: x.jerkface.net
```

پروکسی بالا به ظاهر کار میکنه و پینگ نسبتا خوبی داره ولی اپلیکیشن‌هایی که از wss استفاده میکنن بهش وصل نمیشن. من یه پروکسی دیگه از یه شرکتی رو امتحان کردم و کانفیگشو دیدم که پایین گذاشتم و اون کار کرد و بهش متصل شد. میتونید بهم بگید ماجرا چیه و چطوری درستش کنم؟

```
{
      "name": "x",
      "type": "vmess",
      "server": "x",
      "port": 443,
      "tls": true,
      "sni": "x",
      "cipher": "auto",
      "uuid": "x",
      "alterId": 0,
      "network": "ws",
      "ws-opts":
        {
          "path": "x",
          "headers":
            {
              "host": "x",
            },
        },
    }
```
