### ISSUE TITLE
Docker forwards too many ports. Too much memory is consumed.

### ISSUE THREAD

**Issue by nd4y** [hiddify/Hiddify-Manager#4737]
**Describe the bug**
When running the bash command `bash <(curl https://i.hiddify.com/docker/latest)` the docker process takes up all the memory on the host and the hiddify container does not start

docker-compose.yml contains the following configuration
```yaml
services:
  hiddify:
   <--- TRUNCATED --->
    ports:
      - 443:443
      - 80:80
      - "11000-60000"  #for custom protocols like hysteria tuic wiregaurd
```
The problem is the huge number of ports that are forwarded to the container.
With this number of ports, docker on my host requested about 32GB of RAM

The problem is reproduced on:
Ubuntu 22.04.4 LTS
Docker version 27.0.3, build 7d4bcd8

**To Reproduce**
1. execute `bash <(curl https://i.hiddify.com/docker/latest)`  ( there is currently a problem with latest tag. Applied the workaround described in https://github.com/hiddify/Hiddify-Manager/issues/4726 )

**Expected behavior**
There are a huge number of ports not forwarded in docker-compose.yml

**Screenshots**
I have attached a recording of what the problem looks like.
![bandicam2025-01-0801-54-48-567-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/bf46c70d-0b58-4127-86ea-90ad4ddbb643)

**Additional context**
If you want to give a user access on "any port", you can use network_mode: "host"
